swift: WIP darwin support
- Needs cleanup

- Need to check if swift-nix-toolchain.patch is still necessary.

- Should enable verbose-build, IMHO

- Can we build less? Tweak buildbot_linux preset?

- Currently fails at:

  [3400/3403][ 99%][2567.938s] Performing build step for 'compiler-rt'
  [104/806][ 12%][0.798s] Building C object lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/os_version_check.c.o
  FAILED: lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/os_version_check.c.o
  /tmp/nix-build-swift-5.1.1.drv-0/build/buildbot_linux/llvm-macosx-x86_64/./bin/clang -DKERNEL_USE  -O3 -DNDEBUG -arch x86_64 -isysroot /nix/store/afpv8r50svbrmdmk56wcwpzyp5zac3l5-SDKs/MacOSX10.12.sdk  -isysroot /nix/store/afpv8r50svbrmdmk56wcwpzyp5zac3l5-SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.5 -fPIC -O3 -fvisibility=hidden -DVISIBILITY_HIDDEN -Wall -fomit-frame-pointer -arch x86_64 -mkernel -MD -MT lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/os_version_check.c.o -MF lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/os_version_check.c.o.d -o lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/os_version_check.c.o -c /tmp/nix-build-swift-5.1.1.drv-0/src/llvm/projects/compiler-rt/lib/builtins/os_version_check.c
  /tmp/nix-build-swift-5.1.1.drv-0/src/llvm/projects/compiler-rt/lib/builtins/os_version_check.c:18:10: fatal error: 'TargetConditionals.h' file not found
  #include <TargetConditionals.h>
           ^~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [113/806][ 14%][0.848s] Building C object lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/popcountti2.c.o
  ninja: build stopped: subcommand failed.
  FAILED: tools/clang/runtime/compiler-rt-stamps/compiler-rt-build
  cd /tmp/nix-build-swift-5.1.1.drv-0/build/buildbot_linux/llvm-macosx-x86_64/tools/clang/runtime/compiler-rt-bins && /nix/store/mrz74myz60ig4asl3ldrch86mhwlfsai-cmake-3.18.4/bin/cmake --build . && /nix/store/mrz74myz60ig4asl3ldrch86mhwlfsai-cmake-3.18.4/bin/cmake -E touch /tmp/nix-build-swift-5.1.1.drv-0/build/buildbot_linux/llvm-macosx-x86_64/tools/clang/runtime/compiler-rt-stamps//compiler-rt-build
  ninja: build stopped: subcommand failed.